### ISSUE TITLE
No license for this code

### ISSUE THREAD

**Issue by bsauty** [raventan95/echo-view-classifier#2]
Hello @raventan95, would you mind adding a license in order to allow using this code?
Thanks !

**Comment by raventan95** [comment]
@bsauty , sure I've just done so. Thank you.

**Comment by emmcohen** [comment]
Hello @raventan95 
Is the MIT license applied also to the model weights ?
Thank you !

**Comment by raventan95** [comment]
@emmcohen Yes. 

This project is quite old, I do recommend training your own newer model.
